source :rubygems

gem 'eventmachine',   '~> 0.12'
gem 'uuid',           '~> 2.3'
gem 'json',           '~> 1.4.6'
gem 'celluloid'
gem 'celluloid-io'

group :test do
  gem 'rspec',        '~> 2.0', :require => false
  gem 'rspec-given',  '~> 1.0'
  gem 'flexmock',     '> 0.9', :require => false
  gem 'timecop',      '~> 0.3.5'
  gem 'gimme',        '~> 0.1.7'
end
