source 'https://rubygems.org'

gem 'eventmachine'
gem 'uuid'
gem 'json'
gem 'celluloid'
gem 'celluloid-io'

group :test do
  gem 'rspec',        '~> 2.0', :require => false
  gem 'rspec-given',  '~> 1.0'
  gem 'flexmock',     '> 0.9', :require => false
  gem 'timecop'
end
